### PR TITLE
Completed : `get-jobs` router

### PR DESCRIPTION
**Pull request by Muhammed-Rahif**
## Tasks :-
- [x] Get jobs by page number and count ( default values :- `page = 1`, `count = 12` )

### CODE REVIEW

**Review by Muhammed-Rahif — COMMENTED** [review]
@shamilkotta this also ready for review.

**Review by shamilkotta — APPROVED** [review]
let's merge

**Comment by Muhammed-Rahif** [comment]
@shamilkotta what about conflicts ?!

**Comment by Muhammed-Rahif** [comment]
@shamilkotta are u working on this?

**Comment by shamilkotta** [comment]
> @shamilkotta are u working on this?

conflict resolved
merging now

**Pull request merged**
